name: grassroots_demo
description: A demo flutter project for grassroots

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.0-271.7.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  #ui
  font_awesome_flutter: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/coinIcons/
  fonts:
    - family: Onest
      fonts:
        - asset: assets/fonts/Onest-Medium.ttf
          weight: 400
        - asset: assets/fonts/Onest-Bold.ttf
          weight: 700
